import Footer from "./components/footer";
import Header from "./components/header";
import "./globals.css";
import { Familjen_Grotesk } from "next/font/google";

export const familjenGrotesk = Familjen_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-familjen-grotesk",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={familjenGrotesk.variable}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
